### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by puppinoo** [VivaPayments/API#1197]
Hi,
We are testing your service and we'd like to test transactions and recurring payments. I enabled everything in our security section but we're receiving this error for transactions api call:
"The specified api action is disabled for the merchant 26cac0d8-4f15-4f40-b0a7-c8cf56bf7b9e, please consult the documentation"
Can you enable these features in demo AND production environment please?

EDIT: our main goal is to permit recurring payments with credit cards without the need for the client to execute any login.

Regards.

**Comment by matthewrgourd** [comment]
Hi there, please send your demo and production Merchant IDs to mgourd@vivawallet.com refererencing this issue. Thanks!

**Comment by matthewrgourd** [comment]
Hi @puppinoo, I've checked both your accounts and [recurring transactions](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1transactions~1{Id}/post) is switched on. If you're looking to use [Original Credit Transaction](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1transactions~1{Id}?ServiceId=6/delete), I'm afraid this is only available to businesses in the 'Betting' category. If this applies to you, please email support@vivawallet.com with a request to have it enabled.

**Comment by puppinoo** [comment]
Hi,
Thanks for answering me. I was receiving the error while testing the Simple CheckOut but I switched to "Redirect CheckOut" cause I need to enable recurring payments. With the method I used before the recurring payments were performed automatically. For example I set an "Annual" plan with "Monthly" as period and your gateway at each month for 12 times performed the transaction without the need to execute anything manually and I could intercept the webhook and consolidate the operation. Does your system work in a similar way or after I received the permission by the user to execute the recurring payments I still need to execute them from my system at every exiration date?

Thanks.

**Comment by Reaper1994** [comment]
hi 
I tried implementing the native checkout in  PHP https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/web/index.php

everything works while using the  demo account but when I use the live account I get following error in the console 
![asdsds](https://user-images.githubusercontent.com/23649642/69633677-b493ec80-1076-11ea-88bc-882e0c7a0236.png)

**Comment by matthewrgourd** [comment]
Hi there, can you send me your Merchant ID referencing this issue? My email is mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
@Reaper1994 Have you got a production account? I can't find you on our system. Please send through your Merchant ID once you've set up a live instance...

**Comment by Reaper1994** [comment]
> @Reaper1994 Have you got a production account? I can't find you on our system. Please send through your Merchant ID once you've set up a live [instance...mgourd@vivawallet.com](mailto:instance...mgourd@vivawallet.com) Thanks!
yes  have got a production account

**Comment by Reaper1994** [comment]
> @Reaper1994 Have you got a production account? I can't find you on our system. Please send through your Merchant ID once you've set up a live [instance...mgourd@vivawallet.com](mailto:instance...mgourd@vivawallet.com) Thanks!

@mathewground yes i have a production account

**Comment by matthewrgourd** [comment]
Should work now!

**Comment by Reaper1994** [comment]
> Should work now!

@matthewrgourd 
may I know why it was not working earlier?

also, I get this message now

Sorry, your Order Failed due to Source Default of merchant 476***********
does not support native checkout

do I have o enable anything in the dashboard?

![image006](https://user-images.githubusercontent.com/23649642/69719957-9641f580-1137-11ea-9727-63b305a5c1f9.jpg)
e75

**Comment by matthewrgourd** [comment]
@Reaper1994 Ok, sorry, I've reverted. The integration method in the above screenshot should be 'Redirection/Native Checkout v2'.

**Comment by puppinoo** [comment]
Hi,
I temporarely switched to development of Card tokenization so I let on hold the Simple Checkout dev. Now I need to resume it but I'm still receiveing this "The specified api action is disabled for the merchant 26cac0d8-4f15-4f40-b0a7-c8cf56bf7b9e" in Demo environment when I try to execute this url: "https://demo.vivapayments.com/api/transactions" with this paramenter "PaymentToken", vivaWalletToken (where vivaWalletToken is received from the form submit) and basic authentication (didnt test on Live environment). I don't klnwo how to solve. Please help.

Pino.

**Comment by puppinoo** [comment]
this is one of my attempts. Always returns 
{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 26cac0d8-4f15-4f40-b0a7-c8cf56bf7b9e, please consult the documentation","TimeStamp":"2019-11-27T13:49:00.6578525+02:00","CorrelationId":null,"EventId":0,"Success":false}




`	        String auth =new String(merchant_id + ":" + api_key);
	        byte[] data = auth.getBytes(Charset.defaultCharset());
	        String base64 = new String(new org.apache.commons.codec.binary.Base64().encode(data));
	        
	        HttpClient httpclient;
	        HttpPost httpPost;
	        ArrayList<NameValuePair> postParameters;
	        httpclient = new DefaultHttpClient();
	        httpPost = new HttpPost(url);


            //httpPost.addHeader(HttpHeaders.CONTENT_TYPE, "application/json");
            httpPost.addHeader(HttpHeaders.ACCEPT, "application/json");
            httpPost.addHeader(HttpHeaders.AUTHORIZATION, "Basic " + base64);


	        postParameters = new ArrayList<NameValuePair>();
	        postParameters.add(new BasicNameValuePair("PaymentToken", vivaWalletToken.toString()));

	        httpPost.setEntity(new UrlEncodedFormEntity(postParameters, "UTF-8"));
	        HttpResponse res = httpclient.execute(httpPost);
	        StatusLine statusLine = res.getStatusLine();
	        if(statusLine.getStatusCode() == HttpStatus.SC_OK){
	          ByteArrayOutputStream out = new ByteArrayOutputStream();
	          res.getEntity().writeTo(out);
	          String responseString = out.toString();
	          log.debug("responseString: " + responseString);
	          out.close();
	        } else{
	          //Closes the connection.
	        	res.getEntity().getContent().close();
	          throw new IOException(statusLine.getReasonPhrase());
	        }`

**Comment by matthewrgourd** [comment]
Hi @puppinoo I've changed one of your settings. Can you see if that makes any difference?

**Comment by puppinoo** [comment]
It worked! Thanks a lot.
Now can you tell me what kind of token is this? Is this a charge_token? If not can I use it to obtain a charge_token so I can use simple checkout to create recurring transaction connected to an existing OrderCode?

Thanks again.

**Comment by Reaper1994** [comment]
> @Reaper1994 Ok, sorry, I've reverted. The integration method in the above screenshot should be 'Redirection/Native Checkout v2'.

hi I have changed it to Redirection/Native Checkout v2 still getting the same response

**Comment by Reaper1994** [comment]
> > @Reaper1994 Ok, sorry, I've reverted. The integration method in the above screenshot should be 'Redirection/Native Checkout v2'.
> 
> hi @matthewrgourd I have changed it to Redirection/Native Checkout v2 still getting the same response

I see that I'm facing the same issue as this https://github.com/VivaPayments/API/issues/1229#issue-526618148

Could we get help on figuring out the issue?

Thanks

**Comment by matthewrgourd** [comment]
Hi @Reaper1994 I'm sorry, I don't know what the issue is, I will raise with our development team.

**Comment by matthewrgourd** [comment]
Hi @Reaper1994, should work now. Please close this issue unless you continue to have problems. Thanks!

**Comment by Reaper1994** [comment]
> Hi @Reaper1994, should work now. Please close this issue unless you continue to have problems. Thanks!

hi @matthewrgourd  I'm still facing some issue while making calls to the API I get the following response 
ErrorCode":405,"ErrorText":"Action blocked due to security policy

this is while using the online checkout method


sending you my merchant id via email

Thanks

**Comment by tusharshah1692** [comment]
hi we are trying to make payment using credit card we receive this error 
The merchant with id xxxx does not have a source with code '123' assigned or the source is disabled
