### ISSUE TITLE
The card holder verification process could not be completed successfully please try again.

### ISSUE THREAD

**Issue by sminnovation** [VivaPayments/API#1504]
We are experiencing a high volume of failed MasterCard authentications due to : "The card holder verification process could not be completed successfully please try again." 

Could anyone find out what this error is based on and how to resolve it. This seems to mostly affect MasterCard but may not be limited exclusively to MC. Typically no issues with Visa Debit. 

Richard Steggles is current support contact for this issue for our business. 
Thanks

**Comment by matthewrgourd** [comment]
Hi @sminnovation very sorry to hear this. What is your business name and website address, please? Thanks.

**Comment by matthewrgourd** [comment]
Hi @sminnovation there was a general acquiring outage earlier on today. This problem should now be resolved. Please let me know if any more issues.

**Comment by sminnovation** [comment]
As it happens we are getting further issues . We had error 0 during the outage according to Richard. He says the MC issue as reported is not yet resolved , also that issue, the one I raised that you're replying to has been ongoing for 3 days now.

Thanks


Best Regards,

Tristan Hann

Product Development Specialist

SM Innovation ltd

Unit F8

Inspire Business Park

Carrowreagh Road

Dundonald

BT16 1QT

0044 (0)2895607313



[1476452054600_LOGO]http://www.ziggicig.com

________________________________

**Comment by matthewrgourd** [comment]
@sminnovation I've checked your account again and I can only see one instance of a problem with Mastercard in the last few days. That was on 24th March and the same card failed three times. The issuer reason was 'Insufficient funds'. The cardholder in this instance would need to be advised to add funds before making the payment. I cannot see any other unusual activity relating to Mastercard.

**Comment by sminnovation** [comment]
were getting loads of these. like ten customers per day are having to phone in and we're using our backup worldpay terminal to process the same card and they go through first time.

maybe its a communication issue of some kind . strange that you cant sse anything on your end as they are getting this message so you'd think it would be logged.


Best Regards,

Tristan Hann

Product Development Specialist

SM Innovation ltd

Unit F8

Inspire Business Park

Carrowreagh Road

Dundonald

BT16 1QT

0044 (0)2895607313



[1476452054600_LOGO]http://www.ziggicig.com

________________________________

**Comment by matthewrgourd** [comment]
Hi @sminnovation I can see multiple "Mastercard approved" transactions against your account over the past few weeks. Please close the issue if you feel it to be resolved.

**Comment by sminnovation** [comment]
Okay, so just to be clear in case anyone else gets this , our gateway actually turned out not to be registered to Mastercard. Simple enough and yes, it is now resolved

**Comment by matthewrgourd** [comment]
Hi @sminnovation , sorry to have to ask you this, but how exactly did you register your gateway to Mastercard? I'm trying to find out for future reference!

**Comment by sminnovation** [comment]
Might be licensing, not sure Richard sorted this for us.


Best Regards,

Tristan Hann

Product Development Specialist

SM Innovation ltd

Unit F8

Inspire Business Park

Carrowreagh Road

Dundonald

BT16 1QT

0044 (0)2895607313



[1476452054600_LOGO]http://www.ziggicig.com

________________________________
