### ISSUE TITLE
Woo-commerce plugin new version 3.6.1 fails at reaching payment URL

### ISSUE THREAD

**Issue by lobtx** [VivaPayments/API#1641]
Hello

We meet a really blocking issue since we've update the woo-commerce plugin.
We did not modify any config:
![image](https://user-images.githubusercontent.com/38595388/80513637-a167ae80-897f-11ea-86be-502a0df1da9a.png)

Is there any way to get the previous version archive, which I cannot find on your website?

That is strongly blocking as most of our customers won't be able to place any order since we get back to a correct version !

Thanks

**Comment by matthewrgourd** [comment]
Hi @lobtx sorry to hear this, which version is it you've downloaded so I can check? Is it 3.6.0 or 3.6.1?

**Comment by lobtx** [comment]
We've updated to 3.6.1 yesterday, that update brought the issue.
Then I tried to install 3.6.0 that you linked in another issue (reported by weedy) but the problem still appears.

I don't have any trace of which version was installed before the update (I'm not sure it was 3.6.0, maybe 3.5.x) 

Could you link the latest 3.5.x so I can downgrade and test our plugin?

thanks

**Comment by matthewrgourd** [comment]
Hi @lobtx, would be good to know if the issue is with the updated plugin or your settings. If you wouldn't mind testing with the older version (3.5.7) and letting me know the outcome? Link is below. Thanks!

https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip

Failing that, please check your Merchant ID is entered in the WooCommerce plugin settings exactly as it appears in the Viva Wallet banking app. Also, might be worth changing your API key as it looks a bit weird with the asterisks. Maybe replace these characters? Or did it work before like that?

**Comment by lobtx** [comment]
Problem solved with 3.5.7 version

The problem, in my opinion is that the generated URL to create the payment is malformed in your 3.6.x release. As you can see in the following screenshot
![image](https://user-images.githubusercontent.com/38595388/80585832-40d68100-8a14-11ea-9a14-4e146ffc6f4a.png)

Another old issue can be seen on that screenshot, using chrome I don't get the 3DS confirmaiton code form. And my personal credit card is fully compatible with that process.

Please check this issue, I will reopen my old https://github.com/VivaPayments/API/issues/1372

**Comment by matthewrgourd** [comment]
@lobtx I'm checking with the dev team as a matter of urgency...

**Comment by matthewrgourd** [comment]
@lobtx we've double-checked and there's definitely no issue with version 3.6.1 so not sure what happened there. Must be an anomaly in your setup. As regards the Chrome issue, this was not fixed until after 3.5.7 so you really need to get 3.6.1 working if you can. Please check your Merchant ID is entered in the WooCommerce plugin settings exactly as it appears in the Viva Wallet banking app. Also, might be worth changing your API key as it looks a bit weird with the asterisks you had previously.

**Comment by lobtx** [comment]
It is getting really hard for me to understand what "there's definitely no issue with version 3.6.1" could mean to you.

We checked together that with the same plugin settings, 3.5.7 is working fine and 3.6.1 is not.
Is there any need to change the way we configure our plugin, with version 3.6.1 ? If not it means that there is an issue coming with that new version. 

I will try to modify my API key and remove that asterisks, but if it works it will mean that version 3.6.1 can no longer manage it, and that 3.5.7 could. 

[A bit later after testing] I still get the problem with a clean API key (no asterisk)
![image](https://user-images.githubusercontent.com/38595388/80605761-c74e8b00-8a33-11ea-916f-ce3d76ac1176.png)


I think you should consider that as a customer paying for a service, it is not acceptable to hear from you that there is no issue with new version while the previous version perfectly worked before the upgrade.

**Comment by matthewrgourd** [comment]
@lobtx ok, it's just that we've had over 1000 customers upgrading to the new version and no other  reported issues. Of course, we'll look into the problem you've raised further for you as it's not acceptable. Please bear with me while I speak to our dev team again.

**Comment by lobtx** [comment]
@matthewrgourd ok I can understand that. Sorry for being rude.
If you need time to investigate there is no problem for me to keep working with 3.5.7 version. 
If you still think that the problem is in the settings, I can provide you with the screenshots of our WP and Viva Wallet accounts.

Let me know

Thanks

**Comment by flowerspowercbd** [comment]
hello,

I have the same problem on my website www.flowerspowercbdshop.fr
Error 404. we don't change anything.

![image](https://user-images.githubusercontent.com/61199180/80675646-4637d800-8ab5-11ea-9172-632dff74346e.png)

**Comment by matthewrgourd** [comment]
Hi @lobtx no worries. I've looked into this further and there was a small coding issue with our updated plugin (v 3.6.1). Please [download](https://downloads.wordpress.org/plugin/vivawallet-woocommerce-gateway.zip) version 3.6.2 of our plugin, disable and remove the previous version, add 3.6.2 as a new plugin and enable it. You may need to use our [installation guide](http://developer.vivawallet.com/e-commerce-plugins/woocommerce/) again in case any of your settings need refreshing. Thanks!
