### ISSUE TITLE
Simple Checkout payment returning 500 (Internal Server Error)

### ISSUE THREAD

**Issue by vassilismon85** [VivaPayments/API#1820]
We have integrated Simple Checkout method in a custom eshop of ours.
I am trying both in production and demo environment to make a payment but after the 3d secure verification, I am getting the attached errors.
![StoXeri](https://user-images.githubusercontent.com/69846515/90499379-260a5280-e152-11ea-9ff3-61010759b8cc.jpg)
![Response](https://user-images.githubusercontent.com/69846515/90499460-4508e480-e152-11ea-9d25-b1915c9922ca.jpg)

It seems that the https://demo.vivapayments.com/web/checkout/getpaymenttoken & https://www.vivapayments.com/web/checkout/getpaymenttoken url is not working.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, sorry to hear you're experiencing issues. Can you share with me the HTML you're using for the button with your public key blurred out?

**Comment by vassilismon85** [comment]
![0-02-05-65282ec7f8ca2f8189c8c01d1c10170c37c918b5829e2484f50f6a1159cc1575_de3d1bae](https://user-images.githubusercontent.com/69846515/90509494-109d2480-e162-11ea-975d-96e8e8035d22.jpg)

**Comment by vassilismon85** [comment]
Just to keep in mind, I have this issue the last week, while I have the simple checkout integrated in my software over the past 2 years, and it was working great. The screenshot is from the demo environment, but I have the same problem in the production too

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 I've raised with our development team. I'll get back to you once I've a reply. Thanks.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 my colleagues have looked into this and the reason for the issue is due to a Chrome update that affects cookie handling. We should be able to make the necessary changes to the code in the coming weeks. Unfortunately there is no quick fix as the Chrome update will mean a fundamental revision of the code. In the meantime, you should find it still works in Microsoft Edge and other browsers so please advise your customers of the same if at all possible. Alternatively, we have our [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) solution which doesn't involve a button but an embedded payment form instead. Hope this helps and apologies for any inconvenience caused!

**Comment by genesispro** [comment]
Is there any progress fixing that issue? Advising customers to not use Google Chrome browser is not an option since we are referring to retail customers and not an in-house employees. Other than that native apps that use chromium web browser to browse url pages have no choice other than skipping the native app and moving to a non-chrome browser where in that case customers are not even aware of the page url that is loaded from the native app.

**Comment by matthewrgourd** [comment]
Hi @genesispro not yet, but I'm chasing for an update today.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, @genesispro, I'm advised that a fix was applied last week. Please close this issue if problem is now solved.

**Comment by genesispro** [comment]
I just tried it on the developer server and I still have the same problem

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 is the issue resolved for you? Asking you as the original poster. @genesispro your issue may be different. Please let me have your demo merchant ID as I may need to enable the API for you.

**Comment by vassilismon85** [comment]
@matthewrgourd I still have the same problem. I just tried to pay online via firefox browser and it worked ok, which means that the API is enabled. With the same demo merchant id, via google chrome, followin the same steps, I have the same problem as mentioned above.

**Comment by matthewrgourd** [comment]
Hi @genesispro @vassilismon85 seems to be working fine in Chrome on production but not demo. I'm checking with the developers about the latter. Are you sure you've tested on live? Here's the code I'm using in JSBin:
```
<!DOCTYPE html>
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="[my simple checkout key]"
          data-vp-baseurl="https://www.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="1000"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>
```

**Comment by matthewrgourd** [comment]
Hi guys, apparently there's going to be a release tomorrow for both demo and live to be fixed. Apologies for the wait.

**Comment by matthewrgourd** [comment]
Hi @genesispro, @vassilismon85, I'm advised by our dev team that the fix for production is now live. Regarding the demo environment, this should be available in the next hour. Thanks.

**Comment by matthewrgourd** [comment]
FYI, both environments were updated yesterday evening.

**Comment by vassilismon85** [comment]
@matthewrgourd I just tried it with the demo account, and I still get the same error with Chrome

**Comment by matthewrgourd** [comment]
Sorry to hear this. So that I can test, can I please have the code you're using in plain text, with your public key blurred out? Thanks!

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 I'm opening the below in Chrome for Mac v85 and the process works fine. 
```
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="F3nrgfiPzz/nTH/O/LFu7q8iaBAf9VStbVfypQde9d4="
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="1000"
          data-vp-sourcecode="Default"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>
```

**Comment by genesispro** [comment]
The difference that I can spot between yours and mine is data-vp-sourcecode="Default" and the fact that my js is loaded above the button whereas yours is at the bottom. Would data-vp-sourcecode="Default" make any difference? And would loading at the bottom help it? In the meantime I will give it a try with these 2 options and let you know

<script src="https://demo.vivapayments.com/web/checkout/js"></script>
<button id="vivaButton" type="button"
data-vp-publickey="blahblahblahblahblahblahblahblahblahblah"
data-vp-baseurl="https://demo.vivapayments.com"
data-vp-lang="el"
data-vp-amount="1530"
data-vp-description="Παραγγελία στο OnlineFood" data-vp-disablewallet="true" data-vp-expandcard="true">
</button>

**Comment by genesispro** [comment]
![image](https://user-images.githubusercontent.com/19608478/92484636-9e64b080-f1f2-11ea-8d17-e88fb49bee4c.png)
still the same

**Comment by matthewrgourd** [comment]
Hi @genesispro, please send me your entire page of code as plain text. I will then test in my browser.

**Comment by genesispro** [comment]
> Hi @genesispro, please send me your entire page of code as plain text. I will then test in my browser.

this is a bit too big to send it over... you could try to visit our dev server (https://dev.onlinefood.gr/elink/eshop/en) 
use viva@test.gr and 1234 to login ... add something to the basket and go to the basket to see the html source... you can then try to process the order using the option Mastercard/Visa and see yourself the error

**Comment by matthewrgourd** [comment]
Hi @genesispro, I've made a note of the info supplied and will test this afternoon. In the meantime I will delete from your post for security reasons.

**Comment by matthewrgourd** [comment]
Hi @genesispro, I managed to recreate the issue. I've raised with the development team. I'll let you know when there's an update.

**Comment by matthewrgourd** [comment]
Hi @genesispro latest update is that the production version of Simple Checkout is fine in Chrome now but we're waiting for an update in the sandbox environment. Can you confirm you're having no further issues using Simple Checkout when using the base url?

**Comment by matthewrgourd** [comment]
Hi @genesispro apologies for the extended delay, Simple Checkout is now fixed on demo. Please test again via https://dev.onlinefood.gr/elink/eshop/en.  Thanks!

**Comment by tbatzakas** [comment]
Is this fix still current? Suddenly we experience the same issue in our own implementation of simplecheckout on a site that has been working just fine. The weird thing is that some payments go through, but many others don't, so there isn't a 100% failure. I personally tried with my own card from Eurobank and after confirmation from 3dsecure and Eurobank (OTP or App) I experience the same error as of this issue and the same red X button dialog on vivawallet's form.

**Comment by matthewrgourd** [comment]
Hi @tbatzakas this issue related to Chrome browsers only. Are the failures occurring in relation to customers use a Chrome browser? If that's not the case, then there may be a valid reason for the failures. However, in that case, I would need to research more. Can you give me approximate time and date of 3 examples and I'll check your account. I will also have to take a note of your website address and trading name if you don't mind? Thanks.

**Comment by tbatzakas** [comment]
@matthewrgourd yes the issue is caused on Chrome (I tested on mac OS Catalina). I will try some new transactions and get back to you asap. The website in question is tutors.gr

**Comment by tbatzakas** [comment]
@matthewrgourd I tried again today at 20:55 with a viva card and got the same result. HTTP500 for the getpaymenttoken endpoint. The payment gets as far as 2FA confirmation for the card and then I get presented with a red button with a X on the center like the error above.

**Comment by matthewrgourd** [comment]
Hi @tbatzakas, so that I can investigate further, please share with me the full HTML code you are using, with your public key obscured.

**Comment by tbatzakas** [comment]
Hello

This is integrated on custom nodes in Drupal 7 integration. You need the button html or the full page html? In case you need the full page I have to send you 2 php files (2 drupal custom nodes) for you to check. And ofcourse, this is confidential.

**Comment by matthewrgourd** [comment]
Hi @tbatzakas just the button HTML, please. Thanks!

**Comment by tbatzakas** [comment]
<button type="button"
		class='comple_order_with_viva'
		data-vp-publickey="XXXXXXXXXXXXXX"
		data-vp-baseurl="https://www.vivapayments.com"
		data-vp-lang="el"
		data-vp-amount="<?=$_POST['total_cost']?>"
		data-vp-description="<?=$buy_description?>">
</button>

**Comment by matthewrgourd** [comment]
Hi @tbatzakas can I also have your website address for testing? Thanks...

**Comment by tbatzakas** [comment]
hello, it’s on my previous message, it’s tutors.gr <http://tutors.gr/> You will need to register for a new account and then after validating your email create dummy profile. After that you will need to go through choosing a plan and make a payment.

**Comment by matthewrgourd** [comment]
@tbatzakas sorry, one more thing, I need the company name, registration or VAT number so I can find on our database.

**Comment by tbatzakas** [comment]
ok but i need your private email address in order to continue on this one

**Comment by matthewrgourd** [comment]
mgourd@vivawallet.com but please reference this issue (#1820) for tracking purposes. Thanks.

**Comment by matthewrgourd** [comment]
Hi @tbatzakas I can see that you've had transactions over the past few days so I don't think there's an issue with Simple Checkout. There may be another reason for the payment failure you mentioned from yesterday. We previously had an issue with Chrome but now that's fixed. You had a successful transaction yesterday from one customer so that is yet more evidence that our payment system is working.

**Comment by tbatzakas** [comment]
@matthewrgourd fair point, but since there is an http 500 error on viva server, how can we troubleshoot? My own cards never pass btw. Is there a possibility you can see if there is anything more in your side in your logfiles on the aforementioned datetime of my errorneous transaction?

**Comment by matthewrgourd** [comment]
Hi @tbatzakas, unfortunately I can't work out how to purchase anything. I can see how to contact a tutor, but how do you buy a course? Apologies, but I don't understand Greek and Google Translate is fiddly to use on your site.

**Comment by tbatzakas** [comment]
Hello, you register as a tutor and create a profile to choose a plan. This is the paid service, tou dont buy courses

Στάλθηκε από το iPhone μου

**Comment by matthewrgourd** [comment]
Hi @tbatzakas, thanks. I just tested (with a card with no funds) and there was no API error returned. I'm fairly confident the checkout is working correctly. Can I just check if you're referring to a card payment or a payment through Viva Wallet? (first option, available in Greece only)

**Comment by tbatzakas** [comment]
Στάλθηκε από το iPhone μου
