### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by sudo-rahul** [VivaPayments/API#1839]
Hi,
I've implemented viva wallet api in my project and I've both demo and live accounts.
But both are not working.
On clicking charge button in the checkout form it always redirect to transaction failed page.

Please help !

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul, sorry to hear this. Can you share with me the request log or the actual code you're using? Also the full response log if possible? Are you following our [Native Checkout v2 guide](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) or what part of our [developer portal](https://developer.vivawallet.com/) are you viewing to help you create the implementation? A bit more info will help me a lot!

**Comment by sudo-rahul** [comment]
Hi @matthewrgourd ,
I'm using the Viva wallet API and redirect method with that.

API : https://demo.vivapayments.com/api/orders
which give the resonse like : 
{"OrderCode":8956521306089362,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-09-01T13:53:33.0608166+03:00","CorrelationId":null,"EventId":0,"Success":true}

Redirect to : https://demo.vivapayments.com/web/checkout?ref='.$OrderCode

I've also created a new source under websites and apps section but still it is using the default one.Please help!

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul, sorry, still not sure exactly what you're attempting. Here is a working example in cURL in case that helps:
REQUEST
```
curl -L -X POST 'https://demo.vivapayments.com/api/orders' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic OTZjYjVhMDctNDhjZS00ZDgxLTg3NmQtYTZjM2RmOGRiZDE2OkFEMmUqKA==' \
--data-raw '{
  "Tags": [
    "sample string 1",
    "sample string 2",
    "sample string 3"
  ],
  "Email": "customer@domain.com",
  "Phone": "2117604000",
  "FullName": "Customer Name",
  "PaymentTimeOut": 86400,
  "RequestLang": "en-US",
  "MaxInstallments": 12,
  "AllowRecurring": true,
  "SourceCode": 6190,
  "IsPreAuth": true,
  "Amount": 100,
  "MerchantTrns": "Your reference",
  "CustomerTrns": "Description that the customer sees"
}'
```
RESPONSE
```
{"OrderCode":2657997239166486,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-09-01T17:59:32.3916648+03:00","CorrelationId":null,"EventId":0,"Success":true}
```
Then open https://demo.vivapayments.com/web/checkout?ref=2657997239166486 in a browser.

**Comment by sudo-rahul** [comment]
Hi @matthewrgourd ,
I'm doing exactly same what you have written, and please see the response in the previous comment it's same as your response.
After that I'm redirecting to : 
https://demo.vivapayments.com/web/checkout?ref=8956521306089362

After the payment screen when I click on charge, it took me to :

https://demo.vivapayments.com/web/checkout/result?t=33197103-6ba7-459d-bf28-6401a8d718fc&s=2663173686611666&lang=en-US&eventId=0&eci=1

and shows "The Transaction failed." message.

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul, on demo, when attempting payment, you need to use one of the test cards to trigger the 3DS simulation:

**Visa** 
Card holder’s name: Any
Card number: 4111111111111111
CVV: 111
Expiration date: Any in the future

**Mastercard** 
Card holder’s name: Any
Card number: 5900000000000000022
CVV: 111
Expiration date: Any in the future

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul, we've looked into this a bit further and there is indeed a transaction failed message even if you choose a successful 3DS outcome on demo. I'm raising this with the dev team. However, despite the transaction failed message, please be aware that the URL returned in the browser still contains a transaction ID so the backend functionality is in fact working correctly. I will update you as soon as there's a fix. Thanks.

**Comment by sudo-rahul** [comment]
Hi @matthewrgourd ,
Sure, I'll be waiting for your quick response.
Thanks.

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul, I have raised it and our development team are going to provide a fix in the next release (soon).

**Comment by matthewrgourd** [comment]
Hi @sudo-rahul we released a patch on Monday. Demo should be fine now. Please try again and let me know how you get on. Thanks.

**Comment by icr4** [comment]
@matthewrgourd Looks like this issue is back on demo.vivapayments.com
After typing card informations, it redirects to "Transaction is failed" page (/web2/fail)

Demo merchant ID: 18d9a9f6-5cfd-4255-b915-c66f2fad2b5a
