### ISSUE TITLE
"Place order" button not working

### ISSUE THREAD

**Issue by Gfox1972** [VivaPayments/API#1877]
I have reached out to support but it's taking to long for them to reply (sorry)

On monday I installed an auto address filling app to my wordpress/woocommerce website I quickly noted that the address was NOT being carried over for the transaction and they were then failing!  So I disabled and removed the address / postcode lookup app.

But for whatever reason, it has somehow disabled the "place order" button it does nothing! 

So I uninstalled the Viva Wallet for Woocommerce plugin  and have reinstalled but its still not working!

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, sorry to hear you're unhappy with the level of service from our support team. Did you get a reply in the end or do you still need me to look into this for you? If yes, please let me have your website address  and trading name. Thanks.

**Comment by Gfox1972** [comment]
I'm not unhappy far from it! But they have not 

But yes if you don't mind? 

www.thedreambikecompetition.com 

Vulpes Media limited

I have 3 gateways Viva is the last one and I have just re-enabled it as its been disabled since Monday last week due to this issue

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, I can recreate the issue but I don't immediately know why it's happening. Can you let me know which version of our plugin you're using? (**Plugins > Installed Plugins**). The latest is 1.0.3. If 1.0.3 is installed and you're not getting any errors on the settings page, it may be that one of your other plugins is interfering with ours. Do you have anything special installed for your checkout?

**Comment by Gfox1972** [comment]
I have 1.0.3 installed 

And no its the standard woo commerce checkout form

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, in that case, can you try our plugin on its own? (temporarily disable all other payment gateways).

**Comment by Gfox1972** [comment]
It was working fine alongside the other two

And I have just tried it on its own and nope😕

**Comment by matthewrgourd** [comment]
Very strange. Ok, thanks for trying. We can rule out an incompatibility with other payment plugins. It could be that the plugin that you installed left some database settings behind that won't now revert back. I will need to research further with our plugin developer. I'll get back to you once I've an update.

**Comment by Gfox1972** [comment]
many thanks

**Comment by Gfox1972** [comment]
I have reached out to a new dev company to see if they can look over all the code on my website if they resolve it sooner I will update here.

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, we have released a new version of our plugin, v1.1.0. Please remove the existing one and try this:

[viva-wallet-for-woocommerce-v1.1.0.zip](https://github.com/VivaPayments/API/files/5297593/viva-wallet-for-woocommerce-v1.1.0.zip)

Thanks,

Matt

**Comment by Gfox1972** [comment]
Will updating the original not be enough? 



best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, sure, if you have the option to update, do that instead.

**Comment by Gfox1972** [comment]
It didnt work 😕 

just removed it now uploading it again 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by Gfox1972** [comment]
Hi Matt

ok I removed it 

Uploaded new version added and double checked creds 

processed 2 test purchases using my own card in live env 

I get order processing emails and order completed emails after a good few minutes! 

order is showing completed in WC 

But it is not showing in my Viva account 

Also on both occasion I used safari and was not presented with Apple pay option but this may be a setting on my iMac Im not sure 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, apologies for that, don't know what's going on there. Just to be clear, are we referring to your website at www.thedreambikecompetition.co.uk set up on a payment source of WC-0005? I can't see the Viva Wallet plugin enabled, only Opaya and Totalpro.

**Comment by Gfox1972** [comment]
yes thats correct 

and I disabled it again because even though i renamed “testing do not use” some customers still tried it out and they were unsuccessful too 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by Gfox1972** [comment]
Have just re activated it 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972 thanks! I have recreated the issue. Can you leave enabled while I test with our plugin developer?

**Comment by Gfox1972** [comment]
yeah sure 

does this help 


2020-09-29T08:47:07+00:00 DEBUG 
Viva Wallet Version: 1.1.0

--- LOG STARTS HERE: Check source API call failed. 
Result: {"headers":{},"body":"","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE 




best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
@Gfox1972 thanks very much. We can see that our plugin is experiencing JS errors possibly caused by the theme you're using (or the other plugins. You will need to take the following steps. For these tests, if you have any access to a staging server, this would obviously be beneficial.  

1. Disable all plugins except the Viva Wallet for WooCommerce extension. Attempt a payment. If the same problem occurs, proceed to step 2.
2. Re-enable the other extensions and try an alternative theme for your site. Attempt a payment. If the same problem occurs, proceed to step 3.
3. Disable the other payment plugins again. With the alternative theme still selected, attempt a payment. If the same problem occurs, please let us know.

**Comment by Gfox1972** [comment]
Morning Matthew 

I have the wordpress core and WooCommerce issue sorted and now I have APPLE PAY  👊

Unfortunately the card part is not its creating a completed transaction with in WooCommerce but the transaction is not showing in VW 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, we've just released a new version of the plugin which should fix the issue. I suggest you deactivate and delete all current versions of the plugin and replace with this one:
https://developer.vivawallet.com/downloads/viva-wallet-for-woocommerce_v1.1.1.zip

**Comment by Gfox1972** [comment]
unfortunately the card on the checkout page is still not working 



best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, so sorry to hear that. Can you go into **Plugins > Installed plugins > Viva Wallet for WooCommerce > Settings**. Now click the checkbox to show **Advanced settings** and ensure **WC-0005** is selected in the **Live Source Code List** dropdown. Let me know when this is done and I'll test again.

**Comment by Gfox1972** [comment]
yes it is

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, I've performed another test with the Chrome developer console switched on and can see some errors:

![Screenshot 2020-10-06 at 14 27 40](https://user-images.githubusercontent.com/44943019/95208597-39947a00-07e1-11eb-8309-d08d9adb5701.png)

I spoke with our plugin developer and he's come back with the following based on the above.

- If "logrocket' is a plugin, try disabling as it has an error which could be causing our plugin to malfunction.
- There seem to be some generic JavaScript errors being generated. Get your developer to look into these.
- I also see you do some kind of minimizing of the JS scripts. Our plugin is untested with this implementation in place but should be ok. Worth trying without it, though.

**Comment by Gfox1972** [comment]
removed Log rocket and its working yeh! 

thanks for all your help!
